# -*- coding: utf-8 -*-
"""pyIntro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwoVYeRd3WIcsUNoF_exTiv6zn7rDkWu

variables
"""

x1 = 25 #intger
x2 = 9.5 #double
x3 = "Rostom" #string
x4 = input() #take value form user

print(x1, x2, x3, x4) #print the values

"""operators"""

x1, x2 = 19, 3

sum = x1 + x2
print(sum)

sub = x1 - x2
print(sub)

mul = x1 * x2
print(mul)

pow = x1 ** x2
print(pow)

div = x1 / x2
print(div)

intDiv = x1 // x2
print(intDiv)

mod = x1 % x2
print(mod)

"""boolean expression"""

x1, x2 = 19, 3
print(x1 > x2)
print(x1 == x2)
print(x1 < x2)

print(bool("Hello"))
print(bool(x1))

"""string comparison"""

# the strings compared by lexicographic order
# you can read this to understand comparison
# https://runestone.academy/ns/books/published/javajavajava/comparing-strings.html
x1, x2 = "aaaaaa", "z"
if(x1 > x2) :
  print(x1)
else :
  print(x2)

x1, x2 = "ZZZ", "zzz"
if(x1 > x2) :
  print(x1)
else :
  print(x2)

"""Condition"""

grade=float(input())
if grade>90:
  print('A')
elif grade>80:
  print('B')
elif grade>70:
  print('C')
else:
  print('D')

"""loops

"""

n = int(input())
for i in range(n):
  print(i)

for i in range(0, n):
  print(i)

for i in range(0, n, 2):
  print(i)

i=0
while i<n:
  print(i)
  i+=1

"""functions"""

def Welcome(name):
  print("Hello, I'm "+name)

Welcome("Rostom")

"""list"""

myList = [1, 2, 3, 4]
print(myList)
print(len(myList))
myList[0] = 5
print(myList)
myList.append(6)
print(myList)
myList.insert(1, 7)
print(myList)
myList.remove(2)
print(myList)
myList.pop()
print(myList)
myList.sort()
print(myList)
print(myList.count(5))
print(myList.index(5))
myList.clear()
print(myList)

"""set"""

mySet = {1, 2, 3, 4}
print(mySet)
mySet.add(5)
mySet.add(5)
mySet.add(5)
mySet.add(5)
print(len(mySet))
mySet.update({5, 6, 7})
print(mySet)
mySet.remove(2)
print(mySet)
mySet.pop()
print(mySet)
print(mySet.union({5, 6, 7}))
print(mySet.intersection({5, 6, 7}))
print(mySet.difference({5, 6, 7}))
mySet.clear()
print(mySet)
del mySet